# Generated by Django 5.0.7 on 2024-08-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomtype',
            table='room_type',
        ),
    ]
